spring:
  datasource:
    url: ${FINALE_DB_URL}
    username: ${FINALE_DB_USERNAME}
    password: ${FINALE_DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

app:
  swagger:
    version : "V 1.0.1"
    description : "피날레 백엔드 API 문서 입니다."