spring:
  datasource:
    url: ${FINALE_DB_URL}
    username: ${FINALE_DB_USERNAME}
    password: ${FINALE_DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

server:
  port: 8443
  ssl:
    enabled: true
    key-store: ${KEY_STORE}
    key-store-password: ${KEY_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: finale

app:
  swagger:
    version : "V 1.0.12"
    description : "피날레 백엔드 API 문서 입니다."

# Kakao Login Properties
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri:
    login: ${KAKAO_REDIRECT_LOGIN}
    logout : ${KAKAO_REDIRECT_LOGOUT}
  content-type: application/x-www-form-urlencoded;charset=utf-8
  authorization-grant-type: authorization_code
  #Get
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  user-info-uri: https://kapi.kakao.com/v2/user/me
  logout-uri : https://kauth.kakao.com/oauth/logout
  #Post
  token-uri: https://kauth.kakao.com/oauth/token

custom:
  jwt:
    secretKey: finaleSecretKeyMadeBySeungHoAKADrumJ