spring:
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${FINALE_DB_URL}
    username: ${FINALE_DB_USERNAME}
    password: ${FINALE_DB_PASSWORD}
  #    url: jdbc:h2:mem:test
  #    username: sa
  #    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect

app:
  swagger:
    version : "V 1.0.0"
    description : "피날레 백엔드 API 문서 입니다."