spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

app:
  swagger:
    version : "V 1.0.0"
    description : "피날레 백엔드 API 문서 입니다."