spring:
  datasource:
    url: ${FINALE_DB_URL}
    username: ${FINALE_DB_USERNAME}
    password: ${FINALE_DB_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  swagger:
    version : "V 1.1.15"
    description : "피날레 백엔드 API 문서 입니다."

# Kakao Login Properties
kakao:
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri:
    login: ${KAKAO_REDIRECT_LOGIN}
    login-coach: ${KAKAO_REDIRECT_LOGIN_COACH}
    logout: ${KAKAO_REDIRECT_LOGOUT}
    logout-coach: ${KAKAO_REDIRECT_LOGOUT_COACH}
  content-type: application/x-www-form-urlencoded;charset=utf-8
  authorization-grant-type: authorization_code
  #Get
  authorization-uri: https://kauth.kakao.com/oauth/authorize
  user-info-uri: https://kapi.kakao.com/v2/user/me
  logout-uri : https://kauth.kakao.com/oauth/logout
  #Post
  token-uri: https://kauth.kakao.com/oauth/token

custom:
  jwt:
    secretKey: ${JWT_SECRET_KEY}

# AWS S3
cloud:
  aws:
    s3:
      bucket: ${S3-BUCKET-NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3-BUCKET-ACCESS-KEY}
      secretKey: ${S3-BUCKET-SECRET-KEY}

# cool sms
coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_PASSWORD}
    phoneNumber: ${SMS_PHONE_NUMBER}

# message template
sms:
  templates:
    apply: |
      {name}님, 피겨 레슨 신청이 완료되었습니다.
      ▶ 위치 : {location}
      ▶ 시간 : {days} {startTime}~{endTime}
      
      레슨비는 아래 계좌로 1시간 이내로 송금해주시면 됩니다!
      (대관수업이라 대관비를 내야하기 때문에 계좌이체로 해주셔야하는 점 이해부탁드릴게요)
      ▶ 계좌 : 카카오뱅크 3333153079017 우송원
      ▶ 레슨비 : {cost}
    cancel: |
      {name}님, 피겨 레슨 등록이 취소되었습니다. 확인이 필요하시면 연락주세요.
      ▶ 위치 : {location}
      ▶ 시간 : {days} {startTime}~{endTime}
